import { mutation, query } from "./_generated/server";
import { v } from "convex/values";
import { requireUserId, requireMembership } from "./lib/currentUser";
import { requireServiceSecret } from "./lib/serviceAuth";

const CODE_TTL_MS = 5 * 60 * 1000; // authorization codes live 5 minutes

/**
 * Dynamic Client Registration (RFC 7591). Unauthenticated by design — any MCP
 * client may register. We only store redirect URIs (validated later on every
 * authorize/token call) so registration itself grants no access.
 */
export const registerClient = mutation({
  args: {
    clientId: v.string(),
    clientName: v.optional(v.string()),
    redirectUris: v.array(v.string()),
  },
  handler: async (ctx, { clientId, clientName, redirectUris }) => {
    await ctx.db.insert("oauthClients", {
      clientId,
      clientName,
      redirectUris,
      createdAt: new Date().toISOString(),
    });
  },
});

export const getClient = query({
  args: { clientId: v.string() },
  handler: async (ctx, { clientId }) => {
    return ctx.db
      .query("oauthClients")
      .withIndex("by_client_id", (q) => q.eq("clientId", clientId))
      .unique();
  },
});

/**
 * Called from the /authorize route AFTER the user approved, authenticated as
 * that user via their Convex Auth session. Binds the code to (userId,
 * workspaceId) so the back-channel token exchange never has to trust the
 * client for identity. Returns nothing sensitive; the raw code is generated by
 * the caller and only its hash is stored.
 */
export const createAuthCode = mutation({
  args: {
    codeHash: v.string(),
    clientId: v.string(),
    workspaceId: v.id("workspaces"),
    redirectUri: v.string(),
    codeChallenge: v.string(),
    scope: v.optional(v.string()),
    now: v.number(),
  },
  handler: async (ctx, args) => {
    const userId = await requireUserId(ctx);
    // Caller must be a member of the workspace they're granting access to.
    await requireMembership(ctx, args.workspaceId);
    // Validate the client and redirect URI up front.
    const client = await ctx.db
      .query("oauthClients")
      .withIndex("by_client_id", (q) => q.eq("clientId", args.clientId))
      .unique();
    if (!client) throw new Error("Unknown client");
    if (!client.redirectUris.includes(args.redirectUri)) {
      throw new Error("redirect_uri not registered for this client");
    }
    await ctx.db.insert("oauthCodes", {
      codeHash: args.codeHash,
      clientId: args.clientId,
      userId,
      workspaceId: args.workspaceId,
      redirectUri: args.redirectUri,
      codeChallenge: args.codeChallenge,
      scope: args.scope,
      expiresAt: args.now + CODE_TTL_MS,
      createdAt: new Date().toISOString(),
    });
  },
});

/**
 * Token endpoint back-channel (service-authenticated). Validates a one-time
 * code + PKCE (the caller computed the SHA-256 of the verifier), then mints a
 * workspace-scoped MCP access token by inserting into mcpTokens — the exact
 * same table findByHash reads, so the MCP endpoint needs no changes.
 *
 * Returns the mcpTokens row id; the caller already holds the raw token/hash.
 */
export const exchangeCode = mutation({
  args: {
    _serviceSecret: v.string(),
    codeHash: v.string(),
    clientId: v.string(),
    redirectUri: v.string(),
    computedChallenge: v.string(), // base64url(SHA256(code_verifier))
    accessTokenHash: v.string(),
    encryptedToken: v.string(),
    tokenIv: v.string(),
    now: v.number(),
  },
  handler: async (ctx, args) => {
    requireServiceSecret(args._serviceSecret);
    const code = await ctx.db
      .query("oauthCodes")
      .withIndex("by_hash", (q) => q.eq("codeHash", args.codeHash))
      .unique();
    if (!code) throw new Error("invalid_grant: unknown code");
    if (code.usedAt) throw new Error("invalid_grant: code already used");
    if (code.expiresAt < args.now) throw new Error("invalid_grant: code expired");
    if (code.clientId !== args.clientId) throw new Error("invalid_grant: client mismatch");
    if (code.redirectUri !== args.redirectUri) {
      throw new Error("invalid_grant: redirect_uri mismatch");
    }
    if (code.codeChallenge !== args.computedChallenge) {
      throw new Error("invalid_grant: PKCE verification failed");
    }
    // Single-use: mark consumed before minting.
    await ctx.db.patch(code._id, { usedAt: new Date().toISOString() });

    const tokenId = await ctx.db.insert("mcpTokens", {
      workspaceId: code.workspaceId,
      userId: code.userId,
      tokenHash: args.accessTokenHash,
      encryptedToken: args.encryptedToken,
      tokenIv: args.tokenIv,
      label: `oauth:${args.clientId}`,
      createdAt: new Date().toISOString(),
    });
    return { tokenId, workspaceId: code.workspaceId };
  },
});
